### ISSUE TITLE
JSON special chars

### ISSUE THREAD

**Issue by lukert33** [echoThat/echo_that_api#1]
JSON.parse is pretty broken. When it is called on echo.rb:40, it will break if, for instance, the string  contains a square bracket. This is a problem given that abbreviation in quotes is done with square brackets, for example "For score and seven years ago [...] thank you, and goodnight."

I looked into adding "quirk_mode => true" to the JSON parse call per a stack exchange post but it was no good.

We may need to add escape characters to all string on the front end, before sending them as JSON.

**Comment by jorgerc85** [comment]
Are there any other characters that you know are breaking JSON.parse? I found a possible solution for the URL problem I mentioned at some point earlier but I'll have to take a look at the escaping for the rest of the echo.

**Comment by lukert33** [comment]
This may lead to some more: https://code.google.com/p/json-simple/wiki/EscapingExamples

**Comment by jorgerc85** [comment]
Yes, I had just seen that. I'll let you know how it goes.
